common: &common
  adapter: postgresql
  username: sat_site
  password: sat_site

development:
  <<: *common
  database: sat_site_development

test:
  <<: *common
  database: sat_site_test

production:
  <<: *common
  database: sat_site_production
